version: 2
jobs:
  ruby-2.2:
    docker:
      - image: circleci/ruby:2.2.4
    steps:
      - checkout
      - run: bundle
      - run: rake test
  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: bundle
      - run: rake test
workflows:
  version: 2
  rubies:
    jobs:
      - ruby-2.2
      - ruby-2.5
